### ISSUE TITLE
SDK Issue with PWK?

### ISSUE THREAD

**Issue by ManoMarks** [play-with-docker/play-with-kubernetes.github.io#11]
Not sure why the link in the section

### Accessing the web UI

does not work. App is launched from `term1` but should be running on `term2`. Neither works for the link. It pulls up the page, but nothing shows up. Perhaps something with the app but wanted to make sure there's no issues with the SDK or infra at this point.

**Comment by marcosnils** [comment]
I believe I found the issue mano. Try with the following command instead of `kubectl expose`

`kubectl create service nodeport elastic --node-port=30001 --tcp=9200:9200`. 

Port needs to be from 30000 to 32767 as that's a k8s default restriction

**Comment by marcosnils** [comment]
Fixed by 1521bf2c16a350f1c008f05e8898757a8bfaaa8f
