### ISSUE TITLE
Esc key from inside of vim in terminal does not escape.

### ISSUE THREAD

**Issue by sstern6** [play-with-docker/play-with-kubernetes.github.io#24]
When escaping after editing a file in vim, the escape isnt escaping to allow you to save.

https://github.com/docker/labs/issues/409#event-1604175610

**Comment by ManoMarks** [comment]
I'm unable to reproduce. Can you supply the following information?

* The browser and version you're using
* Your base operating system

**Comment by ManoMarks** [comment]
Closing as there was no more information to replicate
