### ISSUE TITLE
How can I run https://labs.play-with-k8s.com locally ?

### ISSUE THREAD

**Issue by mydockergit** [play-with-docker/play-with-kubernetes.github.io#34]
I really like https://labs.play-with-k8s.com but I want to be able to use it with the timers.

How can I install it on a vmware machine to have a web like https://labs.play-with-k8s.com ?  

I read the readme file but it just show how to install the training site and I want to have the site with the option to run Kubernetes environment like it appears in  https://labs.play-with-k8s.com.

**Comment by marcosnils** [comment]
instructions on how to set it you can be found at https://github.com/play-with-docker/play-with-docker
