### ISSUE TITLE
disk quota exceeded error on https://training.play-with-kubernetes.com/kubernetes-workshop/

### ISSUE THREAD

**Issue by bradydavid** [play-with-docker/play-with-kubernetes.github.io#38]
Not sure if this project is run by the same people from play-with-kubernetes.com. If it is, you get the following error when going through the tutorial from this link https://training.play-with-kubernetes.com/kubernetes-workshop/:

ERROR: Service 'webui' failed to build: open /var/lib/docker/vfs/dir/c43fd9458e2f2836db7a7ff2619e8e79c94db190b665239233efce570fe1f8b9/usr/bin/cut: disk quota exceeded

Specifically the:
docker-compose up

from the dockercoins directory

**Comment by desecho** [comment]
I am getting the same error. Could you specify why the issue was closed?

**Comment by ZachDZimmerman** [comment]
I am receiving the same error as well @marcosnils

**Comment by ZachDZimmerman** [comment]
Worked around this issue by starting over.

**Comment by quickbooks2018** [comment]
Same issue here disk quota exceeded error, Play with Kubernetes is not maintaing the high standards as Play with docker.
