### ISSUE TITLE
labs.play-with-k8s.com down

### ISSUE THREAD

**Issue by daveops1** [play-with-docker/play-with-kubernetes.github.io#73]
Hi there, tried to go to k8s sandbox site but it is down.  Just wanted to report and ask if there will be a fix soon, or if this site is no longer maintained.

![image](https://github.com/play-with-docker/play-with-kubernetes.github.io/assets/10213685/7a2498e7-23f0-4139-a728-99567f9f75d3)

**Comment by daveops1** [comment]
This issue occurs both on and off a VPN, in case that helps provide further information.

**Comment by kamelferrahi** [comment]
Same problem. can't access

**Comment by dev-osama-alharbi** [comment]
Same problem. 
;-(

@marcosnils

**Comment by kayx23** [comment]
Same, still down, following

**Comment by marcosnils** [comment]
should be good now.

**Comment by daveops1** [comment]
It's up!  Thank you @marcosnils :)

**Comment by daveops1** [comment]
It's fixed now, will close.
